version: '3'
services:
  mkdocs:
    image: nginx:latest
    container_name: HappyBirthdayToYou2022
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - 9090:80
    volumes:
      - .:/usr/share/nginx/html/